jlevy/og-equity-compensation

- README.md
Markdown ending italics was missing from this bullet point.
> Fix italics

- README.md
> New section with warrants

- README.md
It'd be good to mention that some companies will withhold shares at tax time to account for it, releasing the employee from the need to write a check.
> RSU tax withholdings

- README.md
Some other definitions cleanups.
> More improvements to equity value, offers, negotiations

- README.md
Hey Guys,
I fixed the links.
XO,
Hope
> Broken/Outdated Links Fix

- README.md
And a few other ongoing improvements.
> Expansions on taxation

- README.md
I added about a dozen links to the first two sections of Offers and Negotiations. Want to make sure this all goes as expected before I add too much more.
> Offers links hope

- README.md
Bunch of small fixes following #102 and #99 
Made a variety of edits on intro to be precise about key points and reduce its length slightly. (It may still be too long.)
Other structural reworking and internal links of early sections esp around seeking professional advice.
I've also added the news emoji, which we need for tax or other recent developments.
Minor restructuring in tax subsections and more internal links.
> Intro edits and other structuring

- README.md
Mostly small things and moving one subsection.
> A few more edits

- README.md
To the extent that the question list is a comprehensive guide to what you should ask a prospective employer, I think this is an important question to ask. Once you've signed your offer letter, you lose your best leverage to ask for extended exercise.
> add question about extended exercise windows

- README.md
Closes #105 
Definitely not married to this wording.
> add question about liquidation overhang

- README.md
Better coverage of the exercise window controversy.
A bit on IPO timeframes, and a great report from Harvard with stats.
> Exercise windows. IPO timeframes. Cleanups.

- README.md
Everything in @RacheltheEditor 's #112 plus some edits as discussed, going to e2.0 for simplicity of review.
> Additions including #112

- README.md
Sync with Josh on addressing these.
> Added 🚧 at RSUs and Stock options

- README.md
I can't PR this w/o r-copy commits! PR to r-copy shows older commits from others as well 😞
> more intro copyedits

- README.md
Added paywall emojis and ran flowmark. Sites listed in commit notes.
> Paywall emojis added

- README.md
- Emoji directly in front of link.
- Also using no space after emoji to make Flowmarked Markdown appear nicer.
> Link emoji consistency.

- README.md
I'm merging this to *another* branch so that we can do a copy edit pass on all my upcoming changes at once without going through the whole doc.
> Mild restructure (startups); BOD, captable; content review

- README.md
The only remaining site that requires login (after third article) is Medium. Another link to a login walled site was removed.
> login emoji added

- README.md
@jlevy see final commit for copy changes from #133
> new material from Jlevy, copyedited

- README.md
More changes on top of last PR, moving separately for review.
> Frontmatter edits

- README.md
cutting down on repetition since sections were combined
combined defs of equity and equity compensation, same reason
> equity comp small restructure

- README.md
+ moved around one paragraph out of place in Tax Basics
> small language clarifications and deletions

- README.md
Corrected broken xrefs found while reviewing mouseovers.
> Fixed broken xrefs

- README.md
> eliding second person in definitions

- README.md
These have already been approved by JL.
> Recommitting lost changes to Extended Exercise Window Debate

- README.md
Bill Clinton's link has been eliminated. I left Social Network because it does not appear to be as bad when forced (with unlikely queries).
> Hope bill clinton

- README.md
That's all, folks!
NOT FLOWMARKED
> Fixed the last smart quotes

- README.md
Updated New Yorker article in Further reading. Was wrong one.
> Hope fr fix

- README.md
> Fix broken definition

- README.md
single instance, secondary sales
> bolding for consistency

- README.md
- Fix badly formatted definition abbreviation on RSUs (breaks search).
- Unbullet areas where it's not needed.
- Add an option pool subsection
- A few copy edits.
- Some paragraph re-breaks.
- Adjust emojis/bullets in a few places.
- Small clarificaiton on restricted stock.
> Small prod edits

- README.md
Prod edits only, plus moving paragraph sandwiched between two defs.
> Prod edits

- README.md
Not sure about that site with 2018 state capital gains taxes. Switched back to old url and will find better link (is surprisingly hard to find).
> Hh update tax links

- README.md
Other small improvements.
Content edits could definitely use a copy editing pass.
> Section rename (Plans and Scenarios)

- README.md
Long, incidental definition, "total rewards" 
Link more appropriate in first instance so moved as well.
> added definition for review

- README.md
looks like one line had not been flow marked in e2.0, so that's there too
> AMT caps consistency

- README.md
I swear this is correct. It's the Tax Foundation.
> cap correction

- README.md
There have been some major 2018 changes to threshholds and exemptions on AMT. I have updated the income threshold in the text and updated two out-of-date links but we should revisit this. While no one wants to be hit with the AMT it looks like recent legislation is making it apply to fewer and fewer, warranting recognition in the text and possibly less severe warnings.
> AMT updates

- README.md
404 on ABA (linked text amended to meet new link. Corrected in RVC and in global defs table.)
> link update

- README.md
> equity copy update

- README.md
-IPO language
-409A and FMV split (WIP, need to change section content around)
> Definitions copy improvements for LPs

- README.md
Moved PDF emoji inside link brackets
> production improvements

- README.md
Updates to introductory lines for clarity of section content in the context of section LPs.
> Section LP language

- README.md
No longer necessary since L is available to hide and show Legend.
> Removed Legend

- README.md
When you will actually will
to 
When you will actually own
> grammar change

- README.md
-new flowmark also affected a few things
-we can work more on this definition, but can't replace it yet with the RVC one because the RVC one is complex and mentions details we don't include in EC.
> add link to RVC

- README.md
Updates and edits from Joe Wallin and Josh. Plus copy and formatting fixes.
> New 2020 updates and fixes
